# Generated by Django 3.0.5 on 2020-04-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profileperson_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileperson',
            name='crp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
