# Generated by Django 3.0.5 on 2020-04-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profileperson_crp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileperson',
            name='location',
            field=models.CharField(max_length=30),
        ),
    ]
