# Generated by Django 3.0.5 on 2020-04-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200424_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileperson',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
