# Generated by Django 3.0.5 on 2020-04-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200424_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileperson',
            name='crp',
        ),
        migrations.AlterField(
            model_name='profileperson',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
