# Generated by Django 3.0.5 on 2020-04-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200425_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileperson',
            name='crp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileperson',
            name='isPsicologo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileperson',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
    ]
