# Generated by Django 3.0.5 on 2020-04-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20200425_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileperson',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
