# Generated by Django 3.0.5 on 2020-04-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200425_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileperson',
            name='bio',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profileperson',
            name='crp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profileperson',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
    ]
